### ISSUE TITLE
运行服务提示一些东西没有定义

### ISSUE THREAD

**Issue by zhongyujian** [dingdayu/adbs#1]
\adbs>go run .
# adbs/shell
shell\shell.go:38:14: undefined: pty.Start
shell\shell.go:110:34: not enough arguments in call to syscall.Syscall
shell\shell.go:111:5: undefined: syscall.SYS_IOCTL
shell\shell.go:113:5: undefined: syscall.TIOCSWINSZ

**Comment by dingdayu** [comment]
很高兴能收到反馈，我更新了 go mod 依赖，可以尝试下面的操作：

```
# 更新一下仓库
git pull
# 自动处理一下依赖
go mod tidy
# 再尝试运行看看
go run .
```
